export const SET_TODO: string = 'SET_TODO'
export const SET_TODOLIST: string = 'SET_TODOLIST'
export const REMOVE_TODO: string = 'REMOVE_TODO'
export const SET_STATUS: string = 'SET_STATUS'
export const SET_DOING: string = 'SET_DOING'